predictor_dir: logs/train_predictor_GFP_0.4_2023_09_21__12_49_34_augment
base_pool_path: data/GFP_stability_percentile_0.4.csv
predictor_type: BaseCNN
rescaling: ratio 
results_file: smoothed  
num_eigenvalues: 50
max_n_seqs: 2_000_000
subsample: 0.1
random_traversal_neighborhood: 15
n_jobs: -1
seed: 42
# evmutation_dist_file: /work/kerr/p450/tunable/results/GFP/inv_log.npz
evmutation_dist_file: null