sample_path: logs_baseline_new/mala_approx_stability_2023_10_01__17_51_27/samples_seed_42.csv
base_pool_path: data/GFP_stability_percentile_0.2_0.4.csv
tmp_dir: tmp_foldx/tmp_
ref_seq_fasta: data/foldx/GFP_reference_seq_aa.fasta
topk1: 128
topk2: 128
repaired_ref_pdb: data/foldx/outputs_af2/ref_seq_af2_Repair.pdb
ground_truth_stability: data/stability/stability_foldx_deduplicate_af2.csv
ground_truth_GFP: data/GFP/GFP_ground_truth_deduplicate.csv
GFP_oracle_dir: logs/oracle_GFP_ggs
foldx_cache: data/foldx/cache.json
selection_method: single_task_selection # topk_selection, nested_selection, random_selection, single_task_selection
