gt_csv_path: data/ParD3/ground_truth_ParD3_E3_E2.csv
base_pool_path: data/ParD3/E2_E3_percentile_0.1_0.4.csv
sample_path: logs_new/train_predictor_E2_0.1_0.4_2023_10_07__17_33_57_augment/samples_20231007-174030/seed_1.csv
num_select: 100
inverse_sign_1: True
inverse_sign_2: True
ref_score_1: null
ref_score_2: null