task: fit_E2
muts_per_seq_param: 1.5
base_pool_path: data/ParD3/E2_E3_percentile_0.1_0.4.csv
oracle_dir: logs_new/train_predictor_E2_0.1_0.4_2023_10_07__22_43_47_augment
seed: 42
num_steps: 100
mutation_sites: [60, 63, 79] # None means no limitations
select_best: False