gt_csv_path: data/gb1/ground_truth_gb1_ddg.csv
base_pool_path: data/gb1/gb1_ddg_percentile_0.0_0.4_99value.csv
sample_path: logs_new/train_predictor_ddg_0_0.4_2023_10_05__15_12_56_agument/samples_20231005-163745/seed_1.csv