task: gb1
muts_per_seq_param: 1.5
base_pool_path: data/gb1/gb1_ddg_percentile_0.0_0.4_99value.csv
oracle_dir: logs_new/train_predictor_gb1_0_0.4_2023_10_05__15_12_17_augment
seed: 42
num_steps: 100
mutation_sites: [38, 39, 40, 53] # None means no limitations
select_best: False